version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: algoliasearch
    versions:
    - 4.8.4
    - 4.8.5
    - 4.8.6
    - 4.9.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: vue-instantsearch
    versions:
    - 3.4.3
    - 3.5.0
    - 3.6.0
  - dependency-name: lodash
    versions:
    - 4.17.20
