language: node_js
node_js:
  - node

jobs:
  include:
    - stage: Deploy
      if: branch = master
      cache: npm
      script:
        - npm i
        - npm run build
      deploy:
        provider: pages
        local_dir: dist/
        target-branch: gh-pages
        name: Travis Deployment Bot
        skip_cleanup: true
        github_token: "$GITHUB_TOKEN"
        fqdn: bufgreencode.com
        on:
          branch: master

notifications:
  email: false
env:
  global:
    - secure: DpNaoqapiRBUjgSYRFZ2YupDQUcBbdn3e1KLEU1LHkRIN/mtD25TXeqJZ93z1daK190QAMrPCve1SU79qKC6Rs6DZ6bCTl6pwjar7eP2zbL4SQx2R+kOhPFY4KBvP/koOrq9/QbLj/i5tzP88lr+fPIfO18Og0MU6xbrGOvEePmoCsJI+cfcM7EW7gDYtltf34VMDY8qRObnzFW1sCCvYcpf9CRdJ0EyF4ThwDYu2chGB/7esj6Wv5/JFonRmdvr3E0ZK2rhNMVIFa7LiINHlc91z+qC3goE8Jc5vOPqqLLv6VfSPxl0Q59rxfOO4TTPkiCISeEd526Y6Tx+So4Vkww2eF83Gnv/BxyoRXos0wrFpQQ/vKOz5GRhiYYfilTG8auPuClqoEBTHh8nGUbdXBW6f+BZkIibG5bpvGcCd/P6G0Hgdi3rZB2onbSBcSSXLc8MLm/sI+8cjIsJ0DcxUH0pwK0dhqYrn1+umXkEVXGp/NXO5sW3q5hmYvdg88sV6t4fCnEwoIKE5U2dK8FKfVS5CisLTkfqVrmQYv3ljmLvYbXlOU/Z6xQQpf6nDYj5pOQ3/7MI33IPCdQYmz7HEEogihbGeazZ/L1nfqdh+kancvQ04EXNjo3MuDjTlGvNy6tX67Nw5FVaAPqVNWyHw8BTH6I9f6qQc2srLGtnKhA=
    - secure: k1kR2vS7zFfYIx+IM+qhfumnGF8HanqVyTaDBO7F+5+N/tAm8WjJIONmJdukC2dGkhe9bsu199zedk2PJngoyY4nig7TAYogQDFylcr1VUebyC781mXPvWKvP4M1/8IaXZ3TqIq1lbrPGONF2kfU8xc84dfegfpZhM1t2zKtr6I54+19H0/YxdBCahZtgCUpJvXW8yA16LVvecIdj/xV/Z5wAoZfXV4QjvORDeRBnwTgGTbtgZTcBK72pRMGy9EznDfopnpdc1ooAfvlqp53ikUziNGlUsFIJPBXHSY9WWJ+mQHd0NvrqTU2t/J1eHRxk55VeOD4Fdw3pQ2bvORGPRttZAg/1qCuBIloAWHCanOz1Yke+87ZJFWM1dAteYu3F7TIyqMqicxV5OIOW0pjn2uxhAmnQxfDpb/WWqJDxqnr+nHWq0tpfcL3rFEPrrIem27hPrpwbKmLKxPttu8ELmXPRPUzLp7QetwUcIrDjrt07tuE70DiJviAogYE31NR6M0nQzHAh0UKmvRX7IG0yDIW8FumL7tXHqfSTLq9NuL57Twpx3jH7Wu8mKe1QWGKhMnDNyeGkiyNzO5ehj95J5IU4nZtOYGOUTtRpZ4/t0LVDaeRrwhomBzMsqg3xF++MBoh9VUQqUFNNfgO5kgpv1DoSUYbXOih101BJdEiacA=
    - secure: dgBIebXOCTqPsejRU9bNs8JCfxk4BQFv/j0rx0I/BxzZf8JRV4Z2aNqfIB4xKxWM0QNIJAhTHT04zUhWZRwfbEQYqkxEeg7mNar+3z9sgRPOMLLmjf/sLFdTFYnemyzoJO9zZAVt2wp9Z3cEOUn4T8ZlpIvKUDM/K7H+4Z3kSveccKs/yms4rRm1+CEUSqWOCoFXs/jcDQRZKCczitn7xmdLobTkIDmi2SD/S+5KfnZMYZQ12KhMHtXcszWclo0wW64Xoxj9fMG/p3Dfvw8yR+TWxV9PmFeohuQ6SlW7BG+BkqUJULQcWt/7fAO80saJ9EpS9Zd6B6QAMTzZqTOTcN6rz4eUIuvwAGO4ty8bXNCMK37maFNdVa47HvPJaDrdYF7qmC1bbE08XoRjkKLO/1Jp2eVnnbpb1U+dLt7QYX8wP/+aggzTvQ1SsiPcuVMg34N7UebabV9WD/d150vmwcsVzwPeLvtY9Uo3GZy+7nRHwyu1GRifORwr71C0O0ycoeEUJpyJ5Vn1yFadyR2iuYjaSiIojxmyOLzCedqqD3rG0BQZf5ApeSb8G5OyelL/B9PaVc7OPesmf/JAvHupOIjNFMgnLpy9hGHGVTqagKLrezwIosq2yH8+pyKtHS0lUU7oc2UGzLe9mchHrs/ULd+6hUkRaJGSdclL5blU9PY=
    - secure: Xot7AtlyhnRNT68j0rH3L+Y06qre+T2AN/mmLqFjfx+QQexSD6gIyhqIr8AyIUE1W/0XGHt4vLtDsiAT8f92jBCVQzs06sUHK1UDazfpm3VZGrGKg/dTFRG9Hap5STAY9Q63G6kZzNLdMAOwe+tx7RxfmKApsSa1solL2VWOEIY/VgCZidCM9HwUozCSC4l2f4Sax9nXemsZXLlDjyWM9GF3cp7vJ/+BsFKFYwM8ajlVIcFFPIRYRp0dJAbHYhx+rnA8rXywtSAwzIHAJhTkiKbwaJo51+087OWydfZjDy4VjcrSfOd0e8+CNOr4HJMBk349W0dmcyFcixfrdq9+DIrw3Vr+VPfdsqwjwPXIgtth1tNdDdLhTcwAWhWqPrVfc5O0XOQk3jrPYXzNPzYD7aphceES6cUO7EGZ3zIRMrIho0ify+wDLcUYZtpqkr8pmYO1jkKzwNqvCSJRlTgjv/uh9q2bhmFGDHvMWoNELpHLPLs0dO8pxOpZCvNcngBKqK2w0uVc3m9TUsOL8OKru2G1vqcMrl6yKbQP/+9QRdKauDtkONSXLq36eGDKms/GYb7sRPAlEvcc2jMR43v9hyhdPSBhmuhoSveg00u2szFaQ7pugTMHL4eivVTe19q45kWxl3BY7uYrQtLuhngSnsZx+tIKBQwZRC2dhZJfzF8=
