language: node_js
node_js:
  - node
jobs:
  include:
    - stage: Deploy
      if: branch = master
      cache: npm
      script:
        - npm i
        - npm build
      deploy:
        provider: pages
        local_dir: dist/
        target-branch: gh-pages
        name: Travis Deployment Bot
        skip_cleanup: true
        github_token: "$GITHUB_TOKEN"
        fqdn: gridsome.bufgreencode.com
        on:
          branch: master
notifications:
  email: false
